---
# Source: product-review-api/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-product-review-api
  namespace: product-review-api
  labels:
    app: product-review-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-review-api
  template:
    metadata:
      labels:
        app: product-review-api
    spec:
      containers:
      - name: product-review-api
        image: hotspurs/product-review-api:a19abea
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 600m
