---
# Source: product-review-api/templates/hpa.yaml
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: release-product-review-api-hpa
  namespace: product-review-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: release-product-review-api
  minReplicas: 2
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
