apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: product-reviews-api
  namespace: argocd
spec:
  destination:
    namespace: product-reviews-api
    server: https://kubernetes.default.svc
  source:
    path: manifests/apps/product-reviews-api
    repoURL: https://github.com/hse-mlds-diploma/argocd.git
    targetRevision: HEAD
  project: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - SyncWave=0